// ============================================================
//  QuizSphere — questions.js
//  100 MCQ + 100 True/False question bank
// ============================================================

const MCQ_BANK = [
  // ── Science ─────────────────────────────────────────────
  { id:"m1",  type:"mcq", question:"What is the chemical symbol for Gold?",                                          options:["Au","Ag","Go","Gd"],     answer:0 },
  { id:"m2",  type:"mcq", question:"How many bones are in the adult human body?",                                    options:["206","208","204","210"],  answer:0 },
  { id:"m3",  type:"mcq", question:"Which planet is known as the Red Planet?",                                       options:["Jupiter","Mars","Venus","Saturn"], answer:1 },
  { id:"m4",  type:"mcq", question:"What is the speed of light in a vacuum (approx)?",                              options:["300,000 km/s","150,000 km/s","450,000 km/s","100,000 km/s"], answer:0 },
  { id:"m5",  type:"mcq", question:"Which gas is most abundant in Earth's atmosphere?",                              options:["Oxygen","Carbon Dioxide","Nitrogen","Argon"], answer:2 },
  { id:"m6",  type:"mcq", question:"What organ produces insulin in the human body?",                                 options:["Liver","Kidney","Pancreas","Stomach"], answer:2 },
  { id:"m7",  type:"mcq", question:"What is the atomic number of Carbon?",                                          options:["4","6","8","12"],         answer:1 },
  { id:"m8",  type:"mcq", question:"Which planet has the most moons?",                                              options:["Jupiter","Saturn","Uranus","Neptune"], answer:1 },
  { id:"m9",  type:"mcq", question:"What is the hardest natural substance on Earth?",                                options:["Quartz","Ruby","Diamond","Platinum"], answer:2 },
  { id:"m10", type:"mcq", question:"What is the powerhouse of the cell?",                                           options:["Nucleus","Ribosome","Mitochondria","Chloroplast"], answer:2 },
  { id:"m11", type:"mcq", question:"Which blood type is known as the universal donor?",                              options:["A+","B+","AB+","O-"],      answer:3 },
  { id:"m12", type:"mcq", question:"What is the chemical formula for water?",                                       options:["HO","H2O","H3O","H2O2"],   answer:1 },
  { id:"m13", type:"mcq", question:"How many chambers does the human heart have?",                                  options:["2","3","4","5"],           answer:2 },
  { id:"m14", type:"mcq", question:"What force keeps planets in orbit around the Sun?",                             options:["Magnetism","Friction","Gravity","Nuclear Force"], answer:2 },
  { id:"m15", type:"mcq", question:"Which element has the symbol 'Fe'?",                                            options:["Fluorine","Iron","Francium","Fermium"], answer:1 },

  // ── Geography ────────────────────────────────────────────
  { id:"m16", type:"mcq", question:"What is the capital of Australia?",                                             options:["Sydney","Melbourne","Brisbane","Canberra"], answer:3 },
  { id:"m17", type:"mcq", question:"Which is the longest river in the world?",                                      options:["Amazon","Nile","Yangtze","Mississippi"], answer:1 },
  { id:"m18", type:"mcq", question:"Mount Everest is located in which mountain range?",                             options:["Alps","Andes","Himalayas","Rockies"], answer:2 },
  { id:"m19", type:"mcq", question:"Which country has the most natural lakes?",                                     options:["Russia","USA","Brazil","Canada"], answer:3 },
  { id:"m20", type:"mcq", question:"What is the smallest country in the world?",                                    options:["Monaco","Nauru","Vatican City","San Marino"], answer:2 },
  { id:"m21", type:"mcq", question:"Which continent is the largest by area?",                                       options:["Africa","Asia","North America","Antarctica"], answer:1 },
  { id:"m22", type:"mcq", question:"The Great Barrier Reef is located off which country's coast?",                  options:["New Zealand","South Africa","Brazil","Australia"], answer:3 },
  { id:"m23", type:"mcq", question:"Which ocean is the largest?",                                                   options:["Atlantic","Indian","Arctic","Pacific"], answer:3 },
  { id:"m24", type:"mcq", question:"Which city is known as the 'Big Apple'?",                                       options:["Chicago","Los Angeles","New York","Las Vegas"], answer:2 },
  { id:"m25", type:"mcq", question:"The Amazon Rainforest is primarily in which country?",                          options:["Colombia","Venezuela","Brazil","Peru"], answer:2 },
  { id:"m26", type:"mcq", question:"Which country is known as the Land of the Rising Sun?",                        options:["China","South Korea","Japan","Thailand"], answer:2 },
  { id:"m27", type:"mcq", question:"What is the capital of Canada?",                                                options:["Toronto","Montreal","Vancouver","Ottawa"], answer:3 },
  { id:"m28", type:"mcq", question:"Which desert is the largest in the world?",                                     options:["Gobi","Sahara","Arabian","Antarctic"], answer:3 },
  { id:"m29", type:"mcq", question:"In which country is the Colosseum located?",                                    options:["Greece","Spain","France","Italy"], answer:3 },
  { id:"m30", type:"mcq", question:"Which country has the largest population?",                                     options:["USA","India","China","Russia"], answer:1 },

  // ── History ──────────────────────────────────────────────
  { id:"m31", type:"mcq", question:"In which year did World War II end?",                                           options:["1943","1944","1945","1946"], answer:2 },
  { id:"m32", type:"mcq", question:"Who was the first President of the United States?",                             options:["John Adams","Thomas Jefferson","Benjamin Franklin","George Washington"], answer:3 },
  { id:"m33", type:"mcq", question:"The Berlin Wall fell in which year?",                                           options:["1987","1988","1989","1991"], answer:2 },
  { id:"m34", type:"mcq", question:"Which empire was ruled by Julius Caesar?",                                      options:["Greek","Roman","Ottoman","Persian"], answer:1 },
  { id:"m35", type:"mcq", question:"Who painted the Mona Lisa?",                                                    options:["Michelangelo","Raphael","Leonardo da Vinci","Caravaggio"], answer:2 },
  { id:"m36", type:"mcq", question:"The French Revolution began in which year?",                                    options:["1776","1789","1799","1804"], answer:1 },
  { id:"m37", type:"mcq", question:"Who discovered penicillin?",                                                    options:["Louis Pasteur","Marie Curie","Alexander Fleming","Edward Jenner"], answer:2 },
  { id:"m38", type:"mcq", question:"Which country did Adolf Hitler lead?",                                          options:["Austria","France","Germany","Italy"], answer:2 },
  { id:"m39", type:"mcq", question:"The first moon landing was in which year?",                                     options:["1965","1967","1969","1971"], answer:2 },
  { id:"m40", type:"mcq", question:"Who was known as the 'Maid of Orléans'?",                                      options:["Mary I","Catherine of Aragon","Joan of Arc","Marie Antoinette"], answer:2 },

  // ── Technology ───────────────────────────────────────────
  { id:"m41", type:"mcq", question:"Who co-founded Apple Inc.?",                                                    options:["Bill Gates","Mark Zuckerberg","Steve Jobs","Elon Musk"], answer:2 },
  { id:"m42", type:"mcq", question:"What does 'HTML' stand for?",                                                   options:["HyperText Markup Language","High Transfer Medium Link","Hyper Tool Making Language","Host Terminal Meta Language"], answer:0 },
  { id:"m43", type:"mcq", question:"What does 'CPU' stand for?",                                                    options:["Central Processing Unit","Computer Power Unit","Core Processing Unit","Control Processing Unit"], answer:0 },
  { id:"m44", type:"mcq", question:"Which company created the Android operating system?",                           options:["Apple","Microsoft","Samsung","Google"], answer:3 },
  { id:"m45", type:"mcq", question:"What programming language is primarily used for web styling?",                  options:["Python","Java","CSS","PHP"], answer:2 },
  { id:"m46", type:"mcq", question:"Who is the founder of Microsoft?",                                              options:["Steve Jobs","Elon Musk","Bill Gates","Jeff Bezos"], answer:2 },
  { id:"m47", type:"mcq", question:"Which social media platform uses the hashtag concept most prominently?",        options:["Facebook","Instagram","Twitter/X","LinkedIn"], answer:2 },
  { id:"m48", type:"mcq", question:"What does 'GPS' stand for?",                                                    options:["Global Position Signal","General Positioning System","Global Positioning System","Ground Pulse System"], answer:2 },
  { id:"m49", type:"mcq", question:"In computing, what is 1 Terabyte equal to?",                                    options:["1000 GB","1024 GB","512 GB","2048 GB"], answer:1 },
  { id:"m50", type:"mcq", question:"Which company owns YouTube?",                                                   options:["Meta","Amazon","Apple","Google"], answer:3 },

  // ── Mathematics ──────────────────────────────────────────
  { id:"m51", type:"mcq", question:"What is the value of π (pi) to two decimal places?",                           options:["3.12","3.14","3.16","3.18"], answer:1 },
  { id:"m52", type:"mcq", question:"What is the square root of 144?",                                               options:["11","12","13","14"],       answer:1 },
  { id:"m53", type:"mcq", question:"What is 15% of 200?",                                                           options:["25","30","35","40"],       answer:1 },
  { id:"m54", type:"mcq", question:"How many sides does a hexagon have?",                                           options:["4","5","6","7"],           answer:2 },
  { id:"m55", type:"mcq", question:"What is 7 × 8?",                                                                options:["54","56","58","64"],       answer:1 },
  { id:"m56", type:"mcq", question:"What is the sum of angles in a triangle?",                                      options:["90°","120°","180°","360°"], answer:2 },
  { id:"m57", type:"mcq", question:"Which is the largest prime number below 20?",                                   options:["17","18","19","16"],       answer:2 },
  { id:"m58", type:"mcq", question:"What is 2 to the power of 10?",                                                 options:["512","1000","1024","2048"], answer:2 },
  { id:"m59", type:"mcq", question:"What is the perimeter of a square with side 5 cm?",                            options:["10 cm","15 cm","20 cm","25 cm"], answer:2 },
  { id:"m60", type:"mcq", question:"What is the Fibonacci sequence? The first two terms are 0 and 1. What is the 7th term?",  options:["8","10","12","13"], answer:3 },

  // ── Literature ───────────────────────────────────────────
  { id:"m61", type:"mcq", question:"Who wrote 'Romeo and Juliet'?",                                                 options:["Charles Dickens","Jane Austen","William Shakespeare","Mark Twain"], answer:2 },
  { id:"m62", type:"mcq", question:"What is the name of the whale in 'Moby Dick'?",                                 options:["White Whale","Moby Dick","Old Man","Captain Ahab"], answer:1 },
  { id:"m63", type:"mcq", question:"Who wrote '1984'?",                                                             options:["Aldous Huxley","George Orwell","H.G. Wells","Ray Bradbury"], answer:1 },
  { id:"m64", type:"mcq", question:"Which novel begins with 'It was the best of times, it was the worst of times'?", options:["Oliver Twist","A Tale of Two Cities","Great Expectations","Bleak House"], answer:1 },
  { id:"m65", type:"mcq", question:"Who wrote 'Pride and Prejudice'?",                                              options:["Emily Brontë","Charlotte Brontë","Jane Austen","George Eliot"], answer:2 },

  // ── Music ────────────────────────────────────────────────
  { id:"m66", type:"mcq", question:"How many strings does a standard guitar have?",                                  options:["4","5","6","7"],           answer:2 },
  { id:"m67", type:"mcq", question:"Which band recorded 'Bohemian Rhapsody'?",                                      options:["The Beatles","Led Zeppelin","Queen","Pink Floyd"], answer:2 },
  { id:"m68", type:"mcq", question:"How many keys does a standard piano have?",                                     options:["76","82","88","92"],       answer:2 },
  { id:"m69", type:"mcq", question:"What is the fastest tempo marking in music?",                                   options:["Allegro","Presto","Vivace","Prestissimo"], answer:3 },
  { id:"m70", type:"mcq", question:"Which instrument is known as the 'King of Instruments'?",                      options:["Violin","Organ","Piano","Trumpet"], answer:1 },

  // ── Sports ───────────────────────────────────────────────
  { id:"m71", type:"mcq", question:"How many players are on a soccer (football) team on the field?",               options:["9","10","11","12"],        answer:2 },
  { id:"m72", type:"mcq", question:"How often are the Summer Olympics held?",                                       options:["Every 2 years","Every 3 years","Every 4 years","Every 5 years"], answer:2 },
  { id:"m73", type:"mcq", question:"In basketball, how many points is a free throw worth?",                        options:["1","2","3","4"],           answer:0 },
  { id:"m74", type:"mcq", question:"Which country invented cricket?",                                               options:["Australia","England","India","South Africa"], answer:1 },
  { id:"m75", type:"mcq", question:"How many holes are in a standard round of golf?",                               options:["9","12","16","18"],        answer:3 },

  // ── General Knowledge ────────────────────────────────────
  { id:"m76", type:"mcq", question:"What is the currency of Japan?",                                                options:["Yuan","Won","Yen","Baht"], answer:2 },
  { id:"m77", type:"mcq", question:"How many colors are in a rainbow?",                                             options:["5","6","7","8"],           answer:2 },
  { id:"m78", type:"mcq", question:"Which language has the most native speakers worldwide?",                        options:["English","Spanish","Hindi","Mandarin Chinese"], answer:3 },
  { id:"m79", type:"mcq", question:"What is the largest organ of the human body?",                                  options:["Liver","Brain","Skin","Heart"], answer:2 },
  { id:"m80", type:"mcq", question:"How many time zones does Russia span?",                                         options:["9","10","11","12"],        answer:2 },
  { id:"m81", type:"mcq", question:"What does 'UNESCO' stand for?",                                                 options:["United Nations Educational, Scientific and Cultural Organization","United Nations Environmental, Social and Cultural Organisation","Universal Nations Education and Cultural Organisation","United Nations Emergency and Social Cooperative Organisation"], answer:0 },
  { id:"m82", type:"mcq", question:"Which animal is the largest living land animal?",                               options:["Hippopotamus","Giraffe","African Elephant","White Rhino"], answer:2 },
  { id:"m83", type:"mcq", question:"What is the most widely spoken language in South America?",                    options:["Spanish","English","French","Portuguese"], answer:3 },
  { id:"m84", type:"mcq", question:"How many planets are in our Solar System?",                                     options:["7","8","9","10"],          answer:1 },
  { id:"m85", type:"mcq", question:"Which vitamin is produced when the skin is exposed to sunlight?",              options:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"], answer:3 },
  { id:"m86", type:"mcq", question:"What is the most popular sport in the world?",                                  options:["Basketball","Cricket","Tennis","Soccer (Football)"], answer:3 },
  { id:"m87", type:"mcq", question:"What year was the United Nations founded?",                                     options:["1943","1944","1945","1946"], answer:2 },
  { id:"m88", type:"mcq", question:"Which animal can survive the longest without water?",                           options:["Camel","Kangaroo Rat","Giraffe","Elephant"], answer:1 },
  { id:"m89", type:"mcq", question:"What is the tallest mountain in Africa?",                                       options:["Mount Kenya","Kilimanjaro","Mount Elgon","Ras Dejen"], answer:1 },
  { id:"m90", type:"mcq", question:"What gas do plants absorb during photosynthesis?",                              options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], answer:1 },
  { id:"m91", type:"mcq", question:"Which country is the largest producer of coffee?",                              options:["Colombia","Ethiopia","Vietnam","Brazil"], answer:3 },
  { id:"m92", type:"mcq", question:"What is the freezing point of water in Celsius?",                               options:["-10°C","0°C","10°C","32°C"], answer:1 },
  { id:"m93", type:"mcq", question:"Which element is used in pencil cores?",                                        options:["Lead","Graphite","Carbon","Charcoal"], answer:1 },
  { id:"m94", type:"mcq", question:"What is the longest bone in the human body?",                                   options:["Humerus","Tibia","Spine","Femur"], answer:3 },
  { id:"m95", type:"mcq", question:"In which year did the Titanic sink?",                                           options:["1910","1912","1914","1916"], answer:1 },
  { id:"m96", type:"mcq", question:"What is the main ingredient in traditional Japanese sushi rice?",              options:["Salt","Rice Vinegar","Soy Sauce","Mirin"], answer:1 },
  { id:"m97", type:"mcq", question:"What colour is the 'black box' flight recorder on airplanes?",                 options:["Black","Grey","Red-Orange","Yellow"], answer:2 },
  { id:"m98", type:"mcq", question:"Who invented the telephone?",                                                   options:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Guglielmo Marconi"], answer:2 },
  { id:"m99", type:"mcq", question:"What is the chemical symbol for Sodium?",                                       options:["So","S","Na","Sd"],        answer:2 },
  { id:"m100",type:"mcq", question:"Which programming language is nicknamed 'the mother of all languages'?",       options:["C","Fortran","COBOL","Assembly"], answer:0 },
];

const TF_BANK = [
  // ── Science ─────────────────────────────────────────────
  { id:"t1",  type:"tf", question:"The Earth is the third planet from the Sun.",                                    answer:true  },
  { id:"t2",  type:"tf", question:"Sound travels faster than light.",                                               answer:false },
  { id:"t3",  type:"tf", question:"Humans use only 10% of their brain.",                                            answer:false },
  { id:"t4",  type:"tf", question:"Oxygen is the most abundant gas in Earth's atmosphere.",                         answer:false },
  { id:"t5",  type:"tf", question:"DNA stands for Deoxyribonucleic Acid.",                                         answer:true  },
  { id:"t6",  type:"tf", question:"A group of lions is called a pride.",                                            answer:true  },
  { id:"t7",  type:"tf", question:"Bats are blind.",                                                                answer:false },
  { id:"t8",  type:"tf", question:"Diamonds are made of carbon.",                                                   answer:true  },
  { id:"t9",  type:"tf", question:"Water boils at 100°C at sea level.",                                            answer:true  },
  { id:"t10", type:"tf", question:"The sun is a planet.",                                                           answer:false },
  { id:"t11", type:"tf", question:"Spiders are classified as insects.",                                             answer:false },
  { id:"t12", type:"tf", question:"The human body has four lungs.",                                                 answer:false },
  { id:"t13", type:"tf", question:"All mammals give birth to live young.",                                          answer:false },
  { id:"t14", type:"tf", question:"Lightning never strikes the same place twice.",                                   answer:false },
  { id:"t15", type:"tf", question:"Penguins live in the Arctic.",                                                   answer:false },
  { id:"t16", type:"tf", question:"The moon has its own light.",                                                    answer:false },
  { id:"t17", type:"tf", question:"Sharks are mammals.",                                                            answer:false },
  { id:"t18", type:"tf", question:"The chemical formula for salt is NaCl.",                                         answer:true  },
  { id:"t19", type:"tf", question:"Venus is the hottest planet in our solar system.",                               answer:true  },
  { id:"t20", type:"tf", question:"Bacteria are eukaryotes.",                                                       answer:false },

  // ── Geography ────────────────────────────────────────────
  { id:"t21", type:"tf", question:"The Sahara is the largest hot desert in the world.",                             answer:true  },
  { id:"t22", type:"tf", question:"Australia is both a country and a continent.",                                   answer:true  },
  { id:"t23", type:"tf", question:"Africa is the smallest continent.",                                              answer:false },
  { id:"t24", type:"tf", question:"The Dead Sea is actually a lake.",                                               answer:true  },
  { id:"t25", type:"tf", question:"Brazil is the only Portuguese-speaking country in South America.",               answer:true  },
  { id:"t26", type:"tf", question:"The Nile River flows from south to north.",                                      answer:true  },
  { id:"t27", type:"tf", question:"Russia is the largest country in the world by area.",                            answer:true  },
  { id:"t28", type:"tf", question:"The Panama Canal connects the Atlantic and Indian Oceans.",                      answer:false },
  { id:"t29", type:"tf", question:"Tokyo is the capital of Japan.",                                                 answer:true  },
  { id:"t30", type:"tf", question:"Greenland is part of the North American continent.",                             answer:true  },

  // ── History ──────────────────────────────────────────────
  { id:"t31", type:"tf", question:"World War I began in 1914.",                                                     answer:true  },
  { id:"t32", type:"tf", question:"Napoleon Bonaparte was from France.",                                            answer:false },
  { id:"t33", type:"tf", question:"The Great Wall of China is visible from space with the naked eye.",              answer:false },
  { id:"t34", type:"tf", question:"Christopher Columbus discovered America in 1492.",                               answer:true  },
  { id:"t35", type:"tf", question:"The pyramids of Giza were built by ancient Romans.",                             answer:false },
  { id:"t36", type:"tf", question:"Abraham Lincoln was the 16th President of the USA.",                             answer:true  },
  { id:"t37", type:"tf", question:"The Cold War was fought with direct military battles between the USA and USSR.", answer:false },
  { id:"t38", type:"tf", question:"Cleopatra was an Egyptian pharaoh.",                                            answer:true  },
  { id:"t39", type:"tf", question:"The Eiffel Tower was built for the 1900 World's Fair.",                         answer:false },
  { id:"t40", type:"tf", question:"India gained independence from Britain in 1947.",                                answer:true  },

  // ── Technology ───────────────────────────────────────────
  { id:"t41", type:"tf", question:"The first iPhone was released in 2007.",                                         answer:true  },
  { id:"t42", type:"tf", question:"Wi-Fi stands for Wireless Fidelity.",                                            answer:false },
  { id:"t43", type:"tf", question:"JavaScript and Java are the same programming language.",                         answer:false },
  { id:"t44", type:"tf", question:"The Internet and the World Wide Web are the same thing.",                        answer:false },
  { id:"t45", type:"tf", question:"HTTP stands for HyperText Transfer Protocol.",                                   answer:true  },
  { id:"t46", type:"tf", question:"Tesla was founded by Elon Musk.",                                                answer:false },
  { id:"t47", type:"tf", question:"Binary code uses only the digits 0 and 1.",                                      answer:true  },
  { id:"t48", type:"tf", question:"The first computer virus was created in the 1970s.",                             answer:true  },
  { id:"t49", type:"tf", question:"RAM stands for Random Access Memory.",                                           answer:true  },
  { id:"t50", type:"tf", question:"Bluetooth was named after a Danish king.",                                       answer:true  },

  // ── General Knowledge ────────────────────────────────────
  { id:"t51", type:"tf", question:"A group of crows is called a murder.",                                           answer:true  },
  { id:"t52", type:"tf", question:"Honey never expires.",                                                           answer:true  },
  { id:"t53", type:"tf", question:"The Great Barrier Reef is the world's largest living structure.",               answer:true  },
  { id:"t54", type:"tf", question:"A marathon is exactly 26.2 miles (42.195 km).",                                  answer:true  },
  { id:"t55", type:"tf", question:"Mount Everest is the tallest mountain measured from sea level.",                 answer:true  },
  { id:"t56", type:"tf", question:"Crocodiles can climb trees.",                                                    answer:true  },
  { id:"t57", type:"tf", question:"Goldfish have a memory of only 3 seconds.",                                      answer:false },
  { id:"t58", type:"tf", question:"The human nose can detect over 1 trillion different scents.",                    answer:true  },
  { id:"t59", type:"tf", question:"Sushi always contains raw fish.",                                                answer:false },
  { id:"t60", type:"tf", question:"A group of flamingos is called a flamboyance.",                                  answer:true  },
  { id:"t61", type:"tf", question:"Coca-Cola was originally green.",                                                answer:false },
  { id:"t62", type:"tf", question:"The currency of the United Kingdom is the Euro.",                                answer:false },
  { id:"t63", type:"tf", question:"Switzerland has four official languages.",                                       answer:true  },
  { id:"t64", type:"tf", question:"Octopuses have three hearts.",                                                   answer:true  },
  { id:"t65", type:"tf", question:"The Statue of Liberty was a gift from France.",                                  answer:true  },
  { id:"t66", type:"tf", question:"All deserts are hot.",                                                           answer:false },
  { id:"t67", type:"tf", question:"Dolphins sleep with one eye open.",                                              answer:true  },
  { id:"t68", type:"tf", question:"The Mona Lisa has no eyebrows.",                                                 answer:true  },
  { id:"t69", type:"tf", question:"A human can hear sounds above 20,000 Hz.",                                      answer:false },
  { id:"t70", type:"tf", question:"The Great Wall of China took less than 100 years to build.",                     answer:false },

  // ── Sports ───────────────────────────────────────────────
  { id:"t71", type:"tf", question:"A standard basketball game consists of four 12-minute quarters (NBA).",         answer:true  },
  { id:"t72", type:"tf", question:"In cricket, a batsman can be out for 'LBW' — Leg Before Wicket.",              answer:true  },
  { id:"t73", type:"tf", question:"Table tennis originated in England.",                                            answer:true  },
  { id:"t74", type:"tf", question:"The FIFA World Cup is held every 4 years.",                                      answer:true  },
  { id:"t75", type:"tf", question:"A standard chess board has 64 squares.",                                         answer:true  },
  { id:"t76", type:"tf", question:"Volleyball was originally called 'mintonette'.",                                 answer:true  },
  { id:"t77", type:"tf", question:"In tennis, a score of 40-40 is called 'Advantage'.",                            answer:false },
  { id:"t78", type:"tf", question:"The penalty spot in soccer is 12 yards from the goal.",                         answer:true  },
  { id:"t79", type:"tf", question:"Swimming was part of the first modern Olympic Games in 1896.",                   answer:true  },
  { id:"t80", type:"tf", question:"A rugby team has 13 players on the field (Rugby League).",                      answer:true  },

  // ── More General ─────────────────────────────────────────
  { id:"t81", type:"tf", question:"The human brain is about 60% fat.",                                              answer:true  },
  { id:"t82", type:"tf", question:"Cats can taste sweetness.",                                                      answer:false },
  { id:"t83", type:"tf", question:"The Great Fire of London happened in 1666.",                                     answer:true  },
  { id:"t84", type:"tf", question:"Bananas are technically berries.",                                               answer:true  },
  { id:"t85", type:"tf", question:"The heart beats approximately 100,000 times a day.",                             answer:true  },
  { id:"t86", type:"tf", question:"Alaska is the largest US state by area.",                                        answer:true  },
  { id:"t87", type:"tf", question:"Elephants are the only animals that cannot jump.",                               answer:false },
  { id:"t88", type:"tf", question:"The original name of Muhammad Ali was Cassius Clay.",                            answer:true  },
  { id:"t89", type:"tf", question:"French fries were invented in France.",                                          answer:false },
  { id:"t90", type:"tf", question:"There are 52 weeks in a standard year.",                                         answer:true  },
  { id:"t91", type:"tf", question:"The Pacific Ocean is larger than all land on Earth combined.",                   answer:true  },
  { id:"t92", type:"tf", question:"A 'fortnight' means two weeks.",                                                 answer:true  },
  { id:"t93", type:"tf", question:"Humans share 50% of their DNA with bananas.",                                    answer:true  },
  { id:"t94", type:"tf", question:"The Caspian Sea is the world's largest ocean.",                                  answer:false },
  { id:"t95", type:"tf", question:"Shakespeare was born and died on the same date: April 23.",                     answer:true  },
  { id:"t96", type:"tf", question:"A day on Venus is longer than a year on Venus.",                                 answer:true  },
  { id:"t97", type:"tf", question:"Glass is a slow-moving liquid.",                                                 answer:false },
  { id:"t98", type:"tf", question:"The Eiffel Tower is taller in summer than in winter.",                          answer:true  },
  { id:"t99", type:"tf", question:"Forks were introduced to the American table in the 17th century.",              answer:false },
  { id:"t100",type:"tf", question:"Catfish have approximately 27,000 taste buds.",                                  answer:true  },
];
